[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
thiserror = "1.0.61"
serde_json = "1.0.116"
serde = { version = "1.0.198", features = ["derive"] }
wgpu = { version = "28.0.0", features = ["metal"] }
bytemuck = { version = "1.24.0", features = ["derive"] }
