import Foundation

// Replace `Integration` with the actual module name generated by UniFFI.
import Integration

/// A long-lived actor wrapper around the UniFFI pipeline.
///
/// Why this shape:
/// - the Rust side keeps the model loaded inside `OnnxRenderPipeline`
/// - the actor gives us serial access, matching the Rust mutex
/// - cross-actor calls naturally use `await`, so camera/UI code stays off the main thread
public actor PhotoStylePipeline {
    private let pipeline: OnnxRenderPipeline

    public init(modelPath: String, metadataPath: String? = nil) throws {
        self.pipeline = try OnnxRenderPipeline(modelPath: modelPath, metadataPath: metadataPath)
    }

    public func inputSize() -> UInt32 {
        pipeline.inputSize()
    }

    public func render(request: FfiOnnxRenderRequest) throws -> FfiOnnxRenderResponse {
        try pipeline.render(request: request)
    }
}

// Example usage from a capture flow:
//
// let pipeline = try PhotoStylePipeline(
//     modelPath: modelPath,
//     metadataPath: metadataPath
// )
//
// Task(priority: .userInitiated) {
//     do {
//         let response = try await pipeline.render(request: request)
//         await MainActor.run {
//             // update preview / UI here
//         }
//     } catch {
//         await MainActor.run {
//             // surface the error here
//         }
//     }
// }
