// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: ai.proto
//

import Connect
import Foundation
import SwiftProtobuf

public protocol Ai_AnalysisClientInterface: Sendable {

    @discardableResult
    func `suggestion`(request: Ai_AnalysisSuggestionRequest, headers: Connect.Headers, completion: @escaping @Sendable (ResponseMessage<Ai_AnalysisSuggestionResponse>) -> Void) -> Connect.Cancelable

    @available(iOS 13, *)
    func `suggestion`(request: Ai_AnalysisSuggestionRequest, headers: Connect.Headers) async -> ResponseMessage<Ai_AnalysisSuggestionResponse>
}

/// Concrete implementation of `Ai_AnalysisClientInterface`.
public final class Ai_AnalysisClient: Ai_AnalysisClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @discardableResult
    public func `suggestion`(request: Ai_AnalysisSuggestionRequest, headers: Connect.Headers = [:], completion: @escaping @Sendable (ResponseMessage<Ai_AnalysisSuggestionResponse>) -> Void) -> Connect.Cancelable {
        return self.client.unary(path: "/ai.Analysis/Suggestion", idempotencyLevel: .unknown, request: request, headers: headers, completion: completion)
    }

    @available(iOS 13, *)
    public func `suggestion`(request: Ai_AnalysisSuggestionRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Ai_AnalysisSuggestionResponse> {
        return await self.client.unary(path: "/ai.Analysis/Suggestion", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let suggestion = Connect.MethodSpec(name: "Suggestion", service: "ai.Analysis", type: .unary)
        }
    }
}
