// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ai.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Ai_AnalysisSuggestionRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var previewImage: Data = Data()

  public var histogram: Data = Data()

  public var sensorStateRequest: Ai_SensorStateRequest {
    get {_sensorStateRequest ?? Ai_SensorStateRequest()}
    set {_sensorStateRequest = newValue}
  }
  /// Returns true if `sensorStateRequest` has been explicitly set.
  public var hasSensorStateRequest: Bool {self._sensorStateRequest != nil}
  /// Clears the value of `sensorStateRequest`. Subsequent reads from it will return its default value.
  public mutating func clearSensorStateRequest() {self._sensorStateRequest = nil}

  public var styleID: String = String()

  public var timeZone: String = String()

  public var timestamp: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _sensorStateRequest: Ai_SensorStateRequest? = nil
}

public struct Ai_SensorStateRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var iso: UInt64 = 0

  public var shutterSpeed: Double = 0

  public var exposureCompensation: Double = 0

  public var aperture: Double = 0

  public var focalLength: Double = 0

  public var width: UInt64 = 0

  public var height: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Ai_AnalysisSuggestionResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var requestID: String = String()

  public var styleID: String = String()

  public var suggestionOptionResponse: Ai_SuggestionOptionResponse {
    get {_suggestionOptionResponse ?? Ai_SuggestionOptionResponse()}
    set {_suggestionOptionResponse = newValue}
  }
  /// Returns true if `suggestionOptionResponse` has been explicitly set.
  public var hasSuggestionOptionResponse: Bool {self._suggestionOptionResponse != nil}
  /// Clears the value of `suggestionOptionResponse`. Subsequent reads from it will return its default value.
  public mutating func clearSuggestionOptionResponse() {self._suggestionOptionResponse = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _suggestionOptionResponse: Ai_SuggestionOptionResponse? = nil
}

public struct Ai_SuggestionOptionResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sceneDescription: String = String()

  public var subjectDescription: String = String()

  public var compositionSuggestion: String = String()

  public var postProcessingResponse: Ai_PostProcessingResponse {
    get {_postProcessingResponse ?? Ai_PostProcessingResponse()}
    set {_postProcessingResponse = newValue}
  }
  /// Returns true if `postProcessingResponse` has been explicitly set.
  public var hasPostProcessingResponse: Bool {self._postProcessingResponse != nil}
  /// Clears the value of `postProcessingResponse`. Subsequent reads from it will return its default value.
  public mutating func clearPostProcessingResponse() {self._postProcessingResponse = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _postProcessingResponse: Ai_PostProcessingResponse? = nil
}

public struct Ai_PostProcessingResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var algorithmID: String = String()

  public var sort: UInt64 = 0

  public var params: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "ai"

extension Ai_AnalysisSuggestionRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AnalysisSuggestionRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}preview_image\0\u{1}histogram\0\u{3}sensor_state_request\0\u{3}style_id\0\u{3}time_zone\0\u{1}timestamp\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.previewImage) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.histogram) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._sensorStateRequest) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.styleID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.timeZone) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.timestamp) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.previewImage.isEmpty {
      try visitor.visitSingularBytesField(value: self.previewImage, fieldNumber: 1)
    }
    if !self.histogram.isEmpty {
      try visitor.visitSingularBytesField(value: self.histogram, fieldNumber: 2)
    }
    try { if let v = self._sensorStateRequest {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if !self.styleID.isEmpty {
      try visitor.visitSingularStringField(value: self.styleID, fieldNumber: 4)
    }
    if !self.timeZone.isEmpty {
      try visitor.visitSingularStringField(value: self.timeZone, fieldNumber: 5)
    }
    if self.timestamp != 0 {
      try visitor.visitSingularUInt64Field(value: self.timestamp, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ai_AnalysisSuggestionRequest, rhs: Ai_AnalysisSuggestionRequest) -> Bool {
    if lhs.previewImage != rhs.previewImage {return false}
    if lhs.histogram != rhs.histogram {return false}
    if lhs._sensorStateRequest != rhs._sensorStateRequest {return false}
    if lhs.styleID != rhs.styleID {return false}
    if lhs.timeZone != rhs.timeZone {return false}
    if lhs.timestamp != rhs.timestamp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Ai_SensorStateRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SensorStateRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}iso\0\u{3}shutter_speed\0\u{3}exposure_compensation\0\u{1}aperture\0\u{3}focal_length\0\u{1}width\0\u{1}height\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.iso) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.shutterSpeed) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.exposureCompensation) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.aperture) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.focalLength) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.width) }()
      case 7: try { try decoder.decodeSingularUInt64Field(value: &self.height) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.iso != 0 {
      try visitor.visitSingularUInt64Field(value: self.iso, fieldNumber: 1)
    }
    if self.shutterSpeed.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.shutterSpeed, fieldNumber: 2)
    }
    if self.exposureCompensation.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.exposureCompensation, fieldNumber: 3)
    }
    if self.aperture.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.aperture, fieldNumber: 4)
    }
    if self.focalLength.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.focalLength, fieldNumber: 5)
    }
    if self.width != 0 {
      try visitor.visitSingularUInt64Field(value: self.width, fieldNumber: 6)
    }
    if self.height != 0 {
      try visitor.visitSingularUInt64Field(value: self.height, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ai_SensorStateRequest, rhs: Ai_SensorStateRequest) -> Bool {
    if lhs.iso != rhs.iso {return false}
    if lhs.shutterSpeed != rhs.shutterSpeed {return false}
    if lhs.exposureCompensation != rhs.exposureCompensation {return false}
    if lhs.aperture != rhs.aperture {return false}
    if lhs.focalLength != rhs.focalLength {return false}
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Ai_AnalysisSuggestionResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AnalysisSuggestionResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0\u{3}style_id\0\u{3}suggestion_option_response\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.styleID) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._suggestionOptionResponse) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 1)
    }
    if !self.styleID.isEmpty {
      try visitor.visitSingularStringField(value: self.styleID, fieldNumber: 2)
    }
    try { if let v = self._suggestionOptionResponse {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ai_AnalysisSuggestionResponse, rhs: Ai_AnalysisSuggestionResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.styleID != rhs.styleID {return false}
    if lhs._suggestionOptionResponse != rhs._suggestionOptionResponse {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Ai_SuggestionOptionResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SuggestionOptionResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}scene_description\0\u{3}subject_description\0\u{3}composition_suggestion\0\u{3}post_processing_response\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.sceneDescription) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.subjectDescription) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.compositionSuggestion) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._postProcessingResponse) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.sceneDescription.isEmpty {
      try visitor.visitSingularStringField(value: self.sceneDescription, fieldNumber: 1)
    }
    if !self.subjectDescription.isEmpty {
      try visitor.visitSingularStringField(value: self.subjectDescription, fieldNumber: 2)
    }
    if !self.compositionSuggestion.isEmpty {
      try visitor.visitSingularStringField(value: self.compositionSuggestion, fieldNumber: 3)
    }
    try { if let v = self._postProcessingResponse {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ai_SuggestionOptionResponse, rhs: Ai_SuggestionOptionResponse) -> Bool {
    if lhs.sceneDescription != rhs.sceneDescription {return false}
    if lhs.subjectDescription != rhs.subjectDescription {return false}
    if lhs.compositionSuggestion != rhs.compositionSuggestion {return false}
    if lhs._postProcessingResponse != rhs._postProcessingResponse {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Ai_PostProcessingResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PostProcessingResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}algorithm_id\0\u{1}sort\0\u{1}params\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.algorithmID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.sort) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.params) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.algorithmID.isEmpty {
      try visitor.visitSingularStringField(value: self.algorithmID, fieldNumber: 1)
    }
    if self.sort != 0 {
      try visitor.visitSingularUInt64Field(value: self.sort, fieldNumber: 2)
    }
    if !self.params.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.params, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ai_PostProcessingResponse, rhs: Ai_PostProcessingResponse) -> Bool {
    if lhs.algorithmID != rhs.algorithmID {return false}
    if lhs.sort != rhs.sort {return false}
    if lhs.params != rhs.params {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
