// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: authentication.proto
//

import Connect
import Foundation
import SwiftProtobuf

public protocol Authentication_AuthnClientInterface: Sendable {

    @discardableResult
    func `up`(request: Authentication_AuthnUpRequest, headers: Connect.Headers, completion: @escaping @Sendable (ResponseMessage<Authentication_AuthnUpResponse>) -> Void) -> Connect.Cancelable

    @available(iOS 13, *)
    func `up`(request: Authentication_AuthnUpRequest, headers: Connect.Headers) async -> ResponseMessage<Authentication_AuthnUpResponse>

    @discardableResult
    func `refresh`(request: Authentication_AuthnRefreshRequest, headers: Connect.Headers, completion: @escaping @Sendable (ResponseMessage<Authentication_AuthnRefreshResponse>) -> Void) -> Connect.Cancelable

    @available(iOS 13, *)
    func `refresh`(request: Authentication_AuthnRefreshRequest, headers: Connect.Headers) async -> ResponseMessage<Authentication_AuthnRefreshResponse>

    @discardableResult
    func `down`(request: Authentication_AuthnDownRequest, headers: Connect.Headers, completion: @escaping @Sendable (ResponseMessage<Authentication_AuthnDownResponse>) -> Void) -> Connect.Cancelable

    @available(iOS 13, *)
    func `down`(request: Authentication_AuthnDownRequest, headers: Connect.Headers) async -> ResponseMessage<Authentication_AuthnDownResponse>
}

/// Concrete implementation of `Authentication_AuthnClientInterface`.
public final class Authentication_AuthnClient: Authentication_AuthnClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @discardableResult
    public func `up`(request: Authentication_AuthnUpRequest, headers: Connect.Headers = [:], completion: @escaping @Sendable (ResponseMessage<Authentication_AuthnUpResponse>) -> Void) -> Connect.Cancelable {
        return self.client.unary(path: "/authentication.Authn/Up", idempotencyLevel: .unknown, request: request, headers: headers, completion: completion)
    }

    @available(iOS 13, *)
    public func `up`(request: Authentication_AuthnUpRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Authentication_AuthnUpResponse> {
        return await self.client.unary(path: "/authentication.Authn/Up", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @discardableResult
    public func `refresh`(request: Authentication_AuthnRefreshRequest, headers: Connect.Headers = [:], completion: @escaping @Sendable (ResponseMessage<Authentication_AuthnRefreshResponse>) -> Void) -> Connect.Cancelable {
        return self.client.unary(path: "/authentication.Authn/Refresh", idempotencyLevel: .unknown, request: request, headers: headers, completion: completion)
    }

    @available(iOS 13, *)
    public func `refresh`(request: Authentication_AuthnRefreshRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Authentication_AuthnRefreshResponse> {
        return await self.client.unary(path: "/authentication.Authn/Refresh", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @discardableResult
    public func `down`(request: Authentication_AuthnDownRequest, headers: Connect.Headers = [:], completion: @escaping @Sendable (ResponseMessage<Authentication_AuthnDownResponse>) -> Void) -> Connect.Cancelable {
        return self.client.unary(path: "/authentication.Authn/Down", idempotencyLevel: .unknown, request: request, headers: headers, completion: completion)
    }

    @available(iOS 13, *)
    public func `down`(request: Authentication_AuthnDownRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Authentication_AuthnDownResponse> {
        return await self.client.unary(path: "/authentication.Authn/Down", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let up = Connect.MethodSpec(name: "Up", service: "authentication.Authn", type: .unary)
            public static let refresh = Connect.MethodSpec(name: "Refresh", service: "authentication.Authn", type: .unary)
            public static let down = Connect.MethodSpec(name: "Down", service: "authentication.Authn", type: .unary)
        }
    }
}
