// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: health.proto
//

import Connect
import Foundation
import SwiftProtobuf

public protocol Health_StatusClientInterface: Sendable {

    @discardableResult
    func `ready`(request: Health_StatusReadyRequest, headers: Connect.Headers, completion: @escaping @Sendable (ResponseMessage<Health_StatusReadyResponse>) -> Void) -> Connect.Cancelable

    @available(iOS 13, *)
    func `ready`(request: Health_StatusReadyRequest, headers: Connect.Headers) async -> ResponseMessage<Health_StatusReadyResponse>
}

/// Concrete implementation of `Health_StatusClientInterface`.
public final class Health_StatusClient: Health_StatusClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @discardableResult
    public func `ready`(request: Health_StatusReadyRequest, headers: Connect.Headers = [:], completion: @escaping @Sendable (ResponseMessage<Health_StatusReadyResponse>) -> Void) -> Connect.Cancelable {
        return self.client.unary(path: "/health.Status/Ready", idempotencyLevel: .unknown, request: request, headers: headers, completion: completion)
    }

    @available(iOS 13, *)
    public func `ready`(request: Health_StatusReadyRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Health_StatusReadyResponse> {
        return await self.client.unary(path: "/health.Status/Ready", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let ready = Connect.MethodSpec(name: "Ready", service: "health.Status", type: .unary)
        }
    }
}
